# Default values for secret-operator.
---
image:
  repository: quay.io/zncdatadev/secret-csi-driver
  pullPolicy: IfNotPresent
  pullSecrets: []


csiDriver:
  # Resources of the secret-operator container itself
  resources:
    requests:
      cpu: 200m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi

csiProvisioner:
  image:
    repository: registry.k8s.io/sig-storage/csi-provisioner
    tag: v5.1.0
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 64Mi
csiNodeDriverRegistrar:
  image:
    repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
    tag: v2.12.0
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 32Mi
livenessProbe:
  image:
    repository: registry.k8s.io/sig-storage/livenessprobe
    tag: v2.14.0
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 32Mi


nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

# Provide additional labels which get attached to all deployed resources
labels:
  kubedoop.dev/vendor: zncdata

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  # secret-operator requires root permissions
  runAsUser: 0
  # It is strongly recommended to run secret-operator as a privileged container, since
  # it enables additional protections for the secret contents.
  # Unprivileged mode is EXPERIMENTAL and requires manual migration for an existing cluster.
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}

# Kubelet dir may vary in environments such as microk8s
kubeletDir: /var/lib/kubelet

secretClasses:
  tls:
    # The namespace that the TLS Certificate Authority is installed into.
    # Defaults to the namespace where secret-op is installed.
    caSecretNamespace: null
    autoGenerated: true

# DaemonSet post-install check
postInstall:
  checkDaemonSet:
    enabled: true
    image: "quay.io/zncdatadev/tools:1.0.0-kubedoop0.0.0-dev"
    attempts: 30
    sleepTime: 10
    backoffLimit: 6
    ttlSecondsAfterFinished: 100
    nodeSelector: {}
    tolerations: []
    # Minimum number of available nodes for the DaemonSet to be considered ready
    # If set to 0, the DaemonSet is considered ready if it is running on at all nodes
    minAvailableNodes: 0
    resources: {}
      # requests:
      #   cpu: 100m
      #   memory: 64Mi
      # limits:
      #   cpu: 200m
      #   memory: 128Mi
