---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-controller
  labels:
    app.kubernetes.io/name: secret-operator
    app.kubernetes.io/instance: secret-operator
    app.kubernetes.io/component: csi-controller
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: secret-operator
      app.kubernetes.io/instance: secret-operator
      app.kubernetes.io/component: csi-controller
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secret-operator
        app.kubernetes.io/instance: secret-operator
        app.kubernetes.io/component: csi-controller
    spec:
      serviceAccountName: controller-manager
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: csi-controller
          image: "csi-plugin:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: ADDRESS
              value: unix:///csi/csi.sock
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
            - --endpoint=$(ADDRESS)
            - --nodeid=$(NODE_NAME)
            - --zap-log-level=2
          resources:
            limits:
              cpu: 512m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-provisioner
          image: "quay.io/zncdatadev/sig-storage/csi-provisioner:v5.1.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: ADDRESS
              value: unix:///csi/csi.sock
          args:
            - --csi-address=$(ADDRESS)
            - --feature-gates=Topology=true
            - --extra-create-metadata
            - --leader-election
            - --timeout=1200s
            - --retry-interval-max=30m
            - --v=2
          resources:
            limits:
              cpu: 128m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: liveness-probe
          image: "quay.io/zncdatadev/sig-storage/livenessprobe:v2.14.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: ADDRESS
              value: unix:///csi/csi.sock
          args:
            - --csi-address=$(ADDRESS)
            - --health-port=9808
            - --probe-timeout=3s
            - --v=2
          ports:
            - containerPort: 9808
              name: healthz
          resources:
            limits:
              cpu: 128m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9808
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9808
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
