---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-controller
  labels:
    app.kubernetes.io/name: secret-operator
    app.kubernetes.io/instance: secret-operator
    app.kubernetes.io/component: csi-controller
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: secret-operator
      app.kubernetes.io/instance: secret-operator
      app.kubernetes.io/component: csi-controller
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: secret-operator
        app.kubernetes.io/instance: secret-operator
        app.kubernetes.io/component: csi-controller
    spec:
      serviceAccountName: controller-manager
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: csi-controller
          image: "csi-plugin:latest"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 512m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 50Mi
          env:
            - name: ADDRESS
              value: unix:///csi/csi.sock
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          args:
            - -endpoint=$(ADDRESS)
            - -nodeid=$(NODE_NAME)
            - -zap-log-level=2
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
          securityContext:
            capabilities:
              drop:
              - ALL
        - name: csi-provisioner
          image: "registry.k8s.io/sig-storage/csi-provisioner:v5.1.0"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: ADDRESS
              value: unix:///csi/csi.sock
          args:
            - --csi-address=$(ADDRESS)
            - --feature-gates=Topology=true
            - --extra-create-metadata
            - --v=2
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: liveness-probe
          image: "registry.k8s.io/sig-storage/livenessprobe:v2.14.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: ADDRESS
              value: unix:///csi/csi.sock
          args:
            - --csi-address=$(ADDRESS)
            - --health-port=9808
            - --v=2
          ports:
            - containerPort: 9808
              name: healthz
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9808
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9808
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
