## Reference: https://github.com/helm/chart-testing/blob/main/doc/ct_lint.md
# Don't add the 'debug' attribute, otherwise the workflow won't work anymore
# Only Used for the CT Lint Stage
chart-dirs:
  - deploy/helm
chart-repos: []
validate-chart-schema: false
validate-maintainers: false
validate-yaml: true
exclude-deprecated: true
check-version-increment: false
excluded-charts: []
