{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}-daemonset
  labels:
    {{- include "operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  - pods
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - listeners.kubedoop.dev
  resources:
  - listeners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.kubedoop.dev
  resources:
  - secretclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.kubedoop.dev
  resources:
  - secretclasses/finalizers
  verbs:
  - update
- apiGroups:
  - secrets.kubedoop.dev
  resources:
  - secretclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - csidrivers
  - storageclasses
  verbs:
  - get
  - list
  - watch
{{- end }}
