---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: secrets.kubedoop.dev
  labels:
  {{- include "operator.labels" . | nindent 4 }}
spec:
  attachRequired: false
  podInfoOnMount: true
  fsGroupPolicy: File
  volumeLifecycleModes:
    - Ephemeral
    - Persistent
