---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "operator.fullname" . }}-daemonset
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "operator.appname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{ .Values.csiDriver.resources | toYaml | nindent 12 }}
          env:
            - name: ADDRESS
              value: unix:///csi/csi.sock
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          args:
            - "-endpoint=$(ADDRESS)"
            - "-nodeid=$(NODE_NAME)"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9808
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9808
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: mountpoint-dir
              mountPath: {{ .Values.kubeletDir }}/pods
              {{- if .Values.securityContext.privileged }}
              mountPropagation: Bidirectional
              {{- end }}
        - name: csi-provisioner
          image: "{{ .Values.csiProvisioner.image.repository }}:{{ .Values.csiProvisioner.image.tag }}"
          imagePullPolicy: {{ .Values.csiProvisioner.image.pullPolicy }}
          resources:
            {{ .Values.csiProvisioner.resources | toYaml | nindent 12 }}
          env:
            - name: ADDRESS
              value: unix:///csi/csi.sock
          args:
            - --csi-address=$(ADDRESS)
            - --feature-gates=Topology=true
            - --extra-create-metadata
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
        - name: node-driver-registrar
          image: "{{ .Values.csiNodeDriverRegistrar.image.repository }}:{{ .Values.csiNodeDriverRegistrar.image.tag }}"
          imagePullPolicy: {{ .Values.csiNodeDriverRegistrar.image.pullPolicy }}
          resources:
            {{ .Values.csiNodeDriverRegistrar.resources | toYaml | nindent 12 }}
          env:
            - name: ADDRESS
              value: unix:///csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: {{ .Values.kubeletDir }}/plugins/secrets.kubedoop.dev/csi.sock
          args:
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
          volumeMounts:
            - name: registration-dir
              mountPath: /registration
            - name: plugin-dir
              mountPath: /csi
        - name: liveness-probe
          image: "{{ .Values.livenessProbe.image.repository }}:{{ .Values.livenessProbe.image.tag }}"
          imagePullPolicy: {{ .Values.livenessProbe.image.pullPolicy }}
          env:
            - name: ADDRESS
              value: unix:///csi/csi.sock
          args:
            - --csi-address=$(ADDRESS)
            - --health-port=9808
          ports:
            - containerPort: 9808
              name: healthz
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9808
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9808
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: registration-dir
          hostPath:
            # node-driver-registrar appends a driver-unique filename to this path to avoid conflicts
            path: {{ .Values.kubeletDir }}/plugins_registry
        - name: plugin-dir
          hostPath:
            type: DirectoryOrCreate
            path: {{ .Values.kubeletDir }}/plugins/secrets.kubedoop.dev/
        - name: mountpoint-dir
          hostPath:
            type: DirectoryOrCreate
            path: {{ .Values.kubeletDir }}/pods/
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
