# permissions for end users to view secretclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}-secretclass-viewer
  labels:
    {{- include "operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
  name: secretclass-viewer-role
rules:
- apiGroups:
  - secrets.kubedoop.dev
  resources:
  - secretclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.kubedoop.dev
  resources:
  - secretclasses/status
  verbs:
  - get
