# permissions for end users to edit secretclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}-secretclass-editor
  labels:
    {{- include "operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
rules:
- apiGroups:
  - secrets.kubedoop.dev
  resources:
  - secretclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.kubedoop.dev
  resources:
  - secretclasses/status
  verbs:
  - get
