apiVersion: secrets.kubedoop.dev/v1alpha1
kind: SecretClass
metadata:
  labels:
    app.kubernetes.io/name: secretclass
    app.kubernetes.io/instance: secretclass-sample
    app.kubernetes.io/part-of: secret-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: secret-operator
  name: secretclass-sample
spec:
  backend:
    k8sSearch:
      searchNamespace:
        name: default
---
apiVersion: secrets.kubedoop.dev/v1alpha1
kind: SecretClass
metadata:
  name: tls
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: secret-operator
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/managed-by: kustomize
spec:
  backend:
    autoTls:
      ca:
        secret:
          name: secret-provisioner-tls-ca
          namespace: kubedoop-operators
        autoGenerate: true
